---
title: "01_case ts"
author: "Brenna Kelly"
date: "2024-07-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(gnm)
library(lme4)
library(dlnm)
library(tidyr)
library(dplyr)
library(stringr)
library(splines)
library(lubridate)
library(data.table)

```

```{r}

## set up exposure
aq <- fread("/Users/brenna/Downloads/clean_dataset.csv")
## outcome
case <- read.csv("/Users/brenna/Downloads/clean_case_data.csv")

```


```{r}

case$birth_date <- as_date(paste(case$birthccyy,
                                 case$birthmm,
                                 case$birthdd, sep = "-"))

case$conception_date <- case$birth_date - (case$gestation)*7
case$conception_week <- case$week - case$gestation
case <- rename(case, birth_week = week)

case <- case |>
  filter(conception_date > "2013-01-01")

# constructing the composite outcome > outcomes related to placental insufficiency
case$pl_insuf <- case_when(case$sga10_by_sex > case$birthweightgrams ~ 1, # sga
                           case$hypertension %in% c("H", "E", "P") ~ 1)
                           # case$placenta_abr == 1 ~ 1)
case$pl_insuf <- ifelse(is.na(case$pl_insuf), 0, 1)

case <- case[, c("grid_id",  "momid", "birth_week",
                 "gestation", "pl_insuf",
                 "conception_week")]


grid_weeks <- case[, c("grid_id", "momid",
                       "conception_week",
                       "birth_week", "pl_insuf")]

expand_preg_fx <- function(x) {
  
  seq.int(x["conception_week"], x["birth_week"], by = 1)
  
}

exp_preg <- apply(grid_weeks, 1, expand_preg_fx)

grid_weeks$exp_preg <- exp_preg

grid_weeks <- grid_weeks |>
  separate(exp_preg, paste0("week_", 0:47)) |>
  select(-week_0)

grid_weeks <- grid_weeks |>
  pivot_longer(c("week_1":"week_47"), 
               names_to = "date_type", values_to = "exposure_week")

## getting exposures for each week of each pregnancy
preg_exp <- merge(grid_weeks, aq, 
                  by.x = c("grid_id", "exposure_week"), 
                  by.y = c("grid_id", "week")) |>
  select(-c("V1"))


## plots
preg_exp$pregnancy_week <- gsub("week_", "", preg_exp$date_type)

early_preg_exp <- preg_exp |>
  mutate(pregnancy_week = as.numeric(pregnancy_week)) |>
  filter(pregnancy_week <= 25)
```



```{r}
## build the cross-basis of pm
cb1.pm <- crossbasis(early_preg_exp$max_pm, 
                     lag = 25, 
                     argvar = list(fun="ns", knots = 3), 
                     arglag = list(fun="ns", knots = 3))
summary(cb1.pm)

## pm
m <- glm(pl_insuf ~ 1 + cb1.pm, # (1 | week)
         data = early_preg_exp, family = "binomial")

pred1.pm <- crosspred(cb1.pm, m, at = 0:200,#0.27:199, 
                      bylag = 1, cumul = TRUE, cen = mean(early_preg_exp$max_pm))

plot(pred1.pm, col = "darkblue")

pred1.pm <- crosspred(cb1.pm, m, at = 150, bylag = 1, cumul = TRUE, 
                      cen = mean(early_preg_exp$mean_pm))

plot(pred1.pm, var = 150, xlim = c(0, 25), xlab = "Lag from 25 (weeks)", ylab = "OR for maxpm = 150",
     ylim = c(0.9, 1.1), lab = c(8, 5, 5), col = 1, lwd = 1.5, ci = "area")
```


beginning at ~70 µg/m³, significant between 5-25 weeks' gestation
relative to average exposure, exposure to 100 µg/m³ increases odds of placental insufficiency by 4.5%
up to 7.5% greater odds of placental insufficiency; exposure 
